/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp6lp1.vistas;

import java.util.Collection;
import java.util.Map;
import java.util.TreeSet;
import javax.swing.table.DefaultTableModel;
import tp6lp1.Cliente;

/**
 *
 * @author FP
 */
public class frm_BuscarTelefonoPorApellido extends javax.swing.JInternalFrame {

    /**
     * Creates new form frm_BuscarTelefonoPorApellido
     */
    public frm_BuscarTelefonoPorApellido() {
        initComponents();
        llenarListaApellidos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtApellido = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblClienteTelefonoPorApellido = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLstListaApellidos = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBtnSalir = new javax.swing.JButton();

        jTxtApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtApellidoFocusGained(evt);
            }
        });
        jTxtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtApellidoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtApellidoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtApellidoKeyTyped(evt);
            }
        });

        jTblClienteTelefonoPorApellido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Apellido", "Nombre", "Direccion", "Ciudad", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTblClienteTelefonoPorApellido.getTableHeader().setResizingAllowed(false);
        jTblClienteTelefonoPorApellido.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTblClienteTelefonoPorApellido);

        jLstListaApellidos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jLstListaApellidosValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jLstListaApellidos);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Buscar Teléfono Por Apellido");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Apellido:");

        jBtnSalir.setText("Salir");
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(243, 243, 243))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBtnSalir)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(48, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBtnSalir)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtApellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtApellidoFocusGained
        limpiarCampos();
    }//GEN-LAST:event_jTxtApellidoFocusGained

    private void jTxtApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtApellidoKeyPressed
    }//GEN-LAST:event_jTxtApellidoKeyPressed

    private void jTxtApellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtApellidoKeyReleased
        llenarListaApellidos();
    }//GEN-LAST:event_jTxtApellidoKeyReleased

    private void jTxtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtApellidoKeyTyped
    }//GEN-LAST:event_jTxtApellidoKeyTyped

    private void limpiarCampos() {
        DefaultTableModel model = (DefaultTableModel) jTblClienteTelefonoPorApellido.getModel();
        model.setRowCount(0);
    };
    
    private void llenarListaApellidos() {
        int largoMapa = MenuPrincipal.getDirectorio().getDirectorio().size();
        String[] apellidos = new String[largoMapa];
        int i = 0;

        Collection<String> setApellidos = new TreeSet();
        for (Cliente cliente : MenuPrincipal.getDirectorio().getDirectorio().values()) {
            //setApellidos.add(cliente.getApellido());
            
            if (setApellidos.add(cliente.getApellido())){
                if (cliente.getApellido().toUpperCase().contains(jTxtApellido.getText().toUpperCase())) {
                apellidos[i] = cliente.getApellido();
                i++;
                }
             };
            };

        jLstListaApellidos.removeAll();
        jLstListaApellidos.setModel(new javax.swing.AbstractListModel<String>() {
            public int getSize() {
                return apellidos.length;
        }
    
            public String getElementAt(int i) {
                return apellidos[i];
            }

        });
    }

    ;
    
      private void llenarTabla(Long telefono, Cliente cliente) {

        DefaultTableModel model = (DefaultTableModel) jTblClienteTelefonoPorApellido.getModel();
        model.addRow(new Object[]{cliente.getDni(), cliente.getApellido(), cliente.getNombre(), cliente.getDireccion(), cliente.getCiudad(), telefono});
    };
    
    private void jLstListaApellidosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jLstListaApellidosValueChanged
        limpiarCampos();
        if (!jLstListaApellidos.isSelectionEmpty()) {
            jTxtApellido.setText(jLstListaApellidos.getSelectedValue());
            for (Map.Entry<Long, Cliente> e : MenuPrincipal.getDirectorio().getDirectorio().entrySet()) {
                String apellido = e.getValue().getApellido();
                if (apellido.equals(jLstListaApellidos.getSelectedValue())) {
                    llenarTabla(e.getKey(), e.getValue());
                }
            }
        }
    }//GEN-LAST:event_jLstListaApellidosValueChanged

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jBtnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jLstListaApellidos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTblClienteTelefonoPorApellido;
    private javax.swing.JTextField jTxtApellido;
    // End of variables declaration//GEN-END:variables
}
