/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tp6lp1.vistas;

import java.util.Map;
import javax.swing.table.DefaultTableModel;
import tp6lp1.Cliente;

public class frm_BorrarCliente extends javax.swing.JInternalFrame {

    /** Creates new form frm_BorrarCliente */
    public frm_BorrarCliente() {
        initComponents();
        llenarListaDni();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLstListaDni = new javax.swing.JList<>();
        jTxtDni = new javax.swing.JTextField();
        jBtnSalir = new javax.swing.JButton();
        jLblTelefono_Dni = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblClienteBorrar = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(654, 401));
        setPreferredSize(new java.awt.Dimension(654, 401));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Borrar Cliente");

        jLstListaDni.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jLstListaDniValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jLstListaDni);

        jTxtDni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtDniFocusGained(evt);
            }
        });
        jTxtDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtDniKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtDniKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtDniKeyTyped(evt);
            }
        });

        jBtnSalir.setText("Salir");
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });

        jLblTelefono_Dni.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLblTelefono_Dni.setText("DNI:");

        jTblClienteBorrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Apellido", "Nombre", "Direccion", "Ciudad", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTblClienteBorrar.getTableHeader().setResizingAllowed(false);
        jTblClienteBorrar.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTblClienteBorrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLblTelefono_Dni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 495, Short.MAX_VALUE)
                                .addComponent(jBtnSalir))
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblTelefono_Dni)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTxtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jBtnSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLstListaDniValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jLstListaDniValueChanged
                limpiarCampos();
                jTxtDni.setText(jLstListaDni.getSelectedValue());
                

               for (Map.Entry<Long,Cliente> e: MenuPrincipal.getDirectorio().getDirectorio().entrySet()) {
                Long dni = e.getValue().getDni();
                if (dni.toString().equals(jLstListaDni.getSelectedValue())){
                  llenarTabla(Long.parseLong(e.getKey().toString()), e.getValue());
                }
            }
    }//GEN-LAST:event_jLstListaDniValueChanged

    private void llenarTabla(Long telefono, Cliente cliente){
        DefaultTableModel model = (DefaultTableModel) jTblClienteBorrar.getModel();
        model.addRow(new Object[]{cliente.getDni(),cliente.getApellido(),cliente.getNombre(),cliente.getDireccion(),cliente.getCiudad(),telefono});
    };
    
    private void limpiarCampos(){
        DefaultTableModel model = (DefaultTableModel) jTblClienteBorrar.getModel();
         model.setRowCount(0);
        
    };
      
    private void llenarListaDni(){
    
    int largoMapa = MenuPrincipal.getDirectorio().getDirectorio().size();
    String[] dniA = new String[largoMapa];
    int i=0;
        jLstListaDni.removeAll();
        
        for (Map.Entry<Long,Cliente> e: MenuPrincipal.getDirectorio().getDirectorio().entrySet()) {
            Long dni = e.getValue().getDni();
            if (dni.toString().contains(jTxtDni.getText())){
            dniA[i]= dni.toString();
            i++;
            }
      }
        
    jLstListaDni.setModel(new javax.swing.AbstractListModel<String>() {
    public int getSize() { return dniA.length; }
    public String getElementAt(int i) { return dniA[i]; }

    });
    }
    
    private void jTxtDniFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtDniFocusGained
        limpiarCampos();
    }//GEN-LAST:event_jTxtDniFocusGained

    private void jTxtDniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtDniKeyPressed

    }//GEN-LAST:event_jTxtDniKeyPressed

    private void jTxtDniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtDniKeyReleased
        llenarListaDni();
    }//GEN-LAST:event_jTxtDniKeyReleased

    private void jTxtDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtDniKeyTyped

    }//GEN-LAST:event_jTxtDniKeyTyped

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblTelefono_Dni;
    private javax.swing.JList<String> jLstListaDni;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTblClienteBorrar;
    private javax.swing.JTextField jTxtDni;
    // End of variables declaration//GEN-END:variables

}
