
package tp6lp1.vistas;

import javax.swing.JInternalFrame;
import tp6lp1.Directorio;
import tp6lp1.clasesdata.CiudadesData;

public class MenuPrincipal extends javax.swing.JFrame {

    private static Directorio directorio=new Directorio();
    private static CiudadesData cData= new CiudadesData();

    public static CiudadesData getcData() {
        return cData;
    }
    
    JInternalFrame ac = new JInternalFrame();
    
    
    public MenuPrincipal() {
        initComponents();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    public static Directorio getDirectorio() {
        return directorio;
    }

     
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMnCliente = new javax.swing.JMenu();
        jMnAgregarCliente = new javax.swing.JMenuItem();
        jMnBuscarCliente = new javax.swing.JMenuItem();
        jMnBorrarCliente = new javax.swing.JMenuItem();
        jMnDirectorio = new javax.swing.JMenu();
        jMCiudades = new javax.swing.JMenu();
        jMnAgregarCiudad = new javax.swing.JMenuItem();
        jMnSalir = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 729, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );

        jMnCliente.setText("Clientes");
        jMnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnClienteActionPerformed(evt);
            }
        });

        jMnAgregarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnAgregarCliente.setText("Agregar Cliente");
        jMnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnAgregarClienteActionPerformed(evt);
            }
        });
        jMnCliente.add(jMnAgregarCliente);

        jMnBuscarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnBuscarCliente.setText("Buscar Cliente");
        jMnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnBuscarClienteActionPerformed(evt);
            }
        });
        jMnCliente.add(jMnBuscarCliente);

        jMnBorrarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnBorrarCliente.setText("Borrar Cliente");
        jMnBorrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnBorrarClienteActionPerformed(evt);
            }
        });
        jMnCliente.add(jMnBorrarCliente);

        jMenuBar1.add(jMnCliente);

        jMnDirectorio.setText("Directorio");
        jMenuBar1.add(jMnDirectorio);

        jMCiudades.setText("Ciudades");
        jMCiudades.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMCiudadesMenuSelected(evt);
            }
        });

        jMnAgregarCiudad.setText("Agregar Ciudad");
        jMnAgregarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnAgregarCiudadActionPerformed(evt);
            }
        });
        jMCiudades.add(jMnAgregarCiudad);

        jMenuBar1.add(jMCiudades);

        jMnSalir.setText("Salir");
        jMnSalir.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMnSalirMenuSelected(evt);
            }
        });
        jMnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMnSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnAgregarClienteActionPerformed

        frm_AgregarCliente vAgregarCliente = new frm_AgregarCliente();
        escritorio.removeAll();
        escritorio.repaint();
        
        vAgregarCliente.setVisible(true);
        escritorio.add(vAgregarCliente);

    }//GEN-LAST:event_jMnAgregarClienteActionPerformed

    private void jMnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnSalirActionPerformed
      
    }//GEN-LAST:event_jMnSalirActionPerformed

    private void jMnSalirMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMnSalirMenuSelected
      System.exit(0);
    }//GEN-LAST:event_jMnSalirMenuSelected

    private void jMnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnClienteActionPerformed
    }//GEN-LAST:event_jMnClienteActionPerformed

    private void jMCiudadesMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMCiudadesMenuSelected
        
         
    }//GEN-LAST:event_jMCiudadesMenuSelected

    private void jMnAgregarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnAgregarCiudadActionPerformed
        frm_AgregarCiudad vAgregarCiudad = new frm_AgregarCiudad();
        escritorio.removeAll();
        escritorio.repaint();
        
        vAgregarCiudad.setVisible(true);
        escritorio.add(vAgregarCiudad);
    }//GEN-LAST:event_jMnAgregarCiudadActionPerformed

    private void jMnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnBuscarClienteActionPerformed

        frm_BuscarClientes vBuscarClientes = new frm_BuscarClientes();
        escritorio.removeAll();
        escritorio.repaint();
        
        vBuscarClientes.setVisible(true);
        escritorio.add(vBuscarClientes);

    }//GEN-LAST:event_jMnBuscarClienteActionPerformed

    private void jMnBorrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnBorrarClienteActionPerformed
     frm_BorrarCliente vBorrarCliente = new frm_BorrarCliente();
        escritorio.removeAll();
        escritorio.repaint();
        
        vBorrarCliente.setVisible(true);
        escritorio.add(vBorrarCliente);

    }//GEN-LAST:event_jMnBorrarClienteActionPerformed

   
    public static void main(String args[]) {
/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMCiudades;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMnAgregarCiudad;
    private javax.swing.JMenuItem jMnAgregarCliente;
    private javax.swing.JMenuItem jMnBorrarCliente;
    private javax.swing.JMenuItem jMnBuscarCliente;
    private javax.swing.JMenu jMnCliente;
    private javax.swing.JMenu jMnDirectorio;
    private javax.swing.JMenu jMnSalir;
    // End of variables declaration//GEN-END:variables
}
